services:
  recoverysky-proxy:
    container_name: recoverysky-proxy
    image: 306057522130.dkr.ecr.us-east-1.amazonaws.com/recoverysky/recoverysky-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
